function catchError(err) {
  // input error object
  // log in the future
  console.error(err);
}

module.exports = {
  catchError: catchError
};
